# Generated by Django 2.0.2 on 2018-12-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=127)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pinyin_key', models.CharField(db_index=True, max_length=127)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('ps', models.TextField()),
            ],
        ),
    ]
